DEMOS = [
    {
        "id": "acoustics",
        "number": "01",
        "title": "Acoustic microscope",
        "short": "Formants & friction",
        "description": "Inspect vowel resonances, the friction spectrum, and timing in a selected sound.",
        "tag": "Measured cues",
    },
    {
        "id": "embeddings",
        "number": "02",
        "title": "Speech embeddings",
        "short": "WavLM & XLS-R",
        "description": "Compare frozen speech representations across recordings and layers.",
        "tag": "Local models",
    },
    {
        "id": "omni",
        "number": "03",
        "title": "Omni audio encoder",
        "short": "Qwen audio features",
        "description": "Explore Qwen's audio representations without loading its language model.",
        "tag": "Encoder only",
    },
    {
        "id": "directions",
        "number": "04",
        "title": "Learn a direction",
        "short": "Labeled contrasts",
        "description": "Fit a small supervised axis and check it on sessions left out of training.",
        "tag": "Supervised probe",
    },
    {
        "id": "articulation",
        "number": "05",
        "title": "Articulation explorer",
        "short": "SPARC trajectories",
        "description": "Explore estimated articulator trajectories in a reference coordinate space.",
        "tag": "Model estimates",
    },
    {
        "id": "calibration",
        "number": "06",
        "title": "Personal calibration",
        "short": "Your accepted examples",
        "description": "Compare a held-out attempt against population references and your personal anchors.",
        "tag": "Reference comparison",
    },
    {
        "id": "providers",
        "number": "07",
        "title": "Assessor comparison",
        "short": "Optional cloud APIs",
        "description": "Compare Azure, SpeechSuper, and an audio language model on the same recording.",
        "tag": "Keys required",
    },
    {
        "id": "feedback",
        "number": "08",
        "title": "Feedback practice",
        "short": "Try, adjust, repeat",
        "description": "Practice along a learned contrast with visual feedback, then test retention without it.",
        "tag": "Practice experiment",
    },
]
